apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-app-mirroring
  namespace: demo-test
spec:
  hosts:
    - demo-app.demo-test.svc.cluster.local
  http:
    - match:
        - sourceLabels:
            app: demo-app
      route:
        - destination:
            host: demo-app.demo-test.svc.cluster.local
            subset: v1
          weight: 100
        mirror:
          host: demo-app.demo-test.svc.cluster.local
          subset: v2
          mirrorPercentage:
            value: 100.0
